services:
  gh-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: gh-proxy:latest
    container_name: gh-proxy
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    network_mode: bridge
